// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingTravel.Models.BookingTravelModels
{
    public partial class City
    {
        public int CityId { get; set; }
        public string Cityname { get; set; }
        public string Citycode { get; set; }
    }
}