// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingTravel.Models.BookingTravelModels
{
    public partial class Country
    {
        public int CountryId { get; set; }
        public string Countryname { get; set; }
        public string Countrycode { get; set; }
        public int? Countryarea { get; set; }
        public string Flagimage { get; set; }
    }
}